version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: yarn start:dev
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
